# MongoDB Connection (Local or Docker)
# spring.mongodb.database=traffic_db

spring.data.mongodb.uri=mongodb+srv://akash_db:Akash%402004@cluster0.jgmdmrs.mongodb.net/traffic_db?retryWrites=true&w=majority&appName=Cluster0

# spring.data.mongodb.uri=mongodb+srv://sadhukhanakash5544:akash@cluster0.83xdfty.mongodb.net/weatherdb?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# Server Port
server.port=8080

# Logging for debugging
logging.level.org.springframework.data.mongodb=DEBUG
