spring.mongodb.uri=mongodb+srv://akash_db:YOUR_PASSWORD@cluster0.jgmdmrs.mongodb.net/traffic_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

server.port=8080
logging.level.org.springframework.data.mongodb=DEBUG
